name: Weekly latest build

on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * 1"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Get latest Bun version
        id: version
        run: echo "VERSION=$(bun --version)" >> $GITHUB_OUTPUT
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
            context: .
            platforms: linux/amd64,linux/arm64
            push: true
            tags: squishyu/bun-alpine:latest,squishyu/bun-alpine:${{ steps.version.outputs.VERSION }}
